![1200px-Python-logo-notext.svg.jpg](attachment:1200px-Python-logo-notext.svg.jpg)

In [ ]:
!pip install opencv-python

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: opencv-python in /usr/local/lib/python3.7/dist-packages (4.6.0.66)
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.7/dist-packages (from opencv-python) (1.21.6)

# <span style='color:blue'> Python </span>
---

In [1]:
import cv2

## What is Python?

Python is an interpreted high-level general-purpose programming language. Its design philosophy emphasizes code readability with its use of significant indentation. Its language constructs as well as its object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.

## Why python?

The python language is one of the most accessible programming languages available because it has simplified syntax and not complicated, which gives more emphasis on natural language. Due to its ease of learning and usage, python codes can be easily written and executed much faster than other programming languages.

In [ ]:
# if we requir the introduction of jupytere notebook and installling of python in our computer

In [ ]:
# syntax in python to print hello world
# simple print statement is used to print anything followed by parenthesis " () "

In [ ]:
print("Hello World")

Hello World

In [ ]:
# If we want to print a string then we have to put that string in double-quotes
# single quotes are used to for regular expressions but double quotes are specially used for string

## Commenting in python

Commenting in pyhton is done by placing a hash-tag and that is followed by the comment we need to write

In [ ]:
# This is a comment

If there is multiple line comment then we will use tripple quotes and it will automatically generate another set of triple quotes in that we can write any comment we want to, and can change the line

In [ ]:
#@title Default title text
""" 
This is 
a multiple
line comment
"""

' \nThis is \na multiple\nline comment\n'

In [ ]:
"""
this my 
first multiple 
line comment 
"""

'\nthis my \nfirst multiple \nline comment \n'

# <span style='color:blue'> Python Variables </span>
---

## Variables Basic

Variables are containers for storing data values.
There is no command for declaring a variable. A variable is created the moment you first assign a value to it.

In [ ]:
# example of declaring variable
var_1 = 10
# Here is a variable we have declared and gave the value 10 to it.
print(var_1)

10

In [ ]:

var_2 = 5
print(var_2)

5

- We can also state the type of variable we are declaring in python just by that variable name followed by its type and in parenthesis we give its value

In [ ]:
var_2 = float(10)
print(var_2)

10.0

In [ ]:
# We can also check the type of variable using inbuild function type()
type(var_2) # here it states that the variable named var_2 is of fload type

float

In [ ]:
# strings variables are always declared either by using single of double quotes
string1 = "My name is " 
type(string1) # checking its type

str

In [ ]:
"""These variables are case sensitive.
 If a variable is named 'a' and another variable is named 'A', then 'A' variable will not overright 'a'"""

"These variables are case sensitive.\n If a variable is named 'a' and another variable is named 'A', then 'A' variable will not overright 'a'"

## Variables Naming

Variables can have a short name (a,b,c) or they can also have more explanatory name (age, name, total_volume).
There are certain things that we keep in mind before declaring a variable.

- It should start with a letter or underscore
- It can't start with a number
- It can only contain alpha-numeric characters and underscore in it. ( A-z, 0-9, _ )

## Ways to define a variable

- Assigning many values to multiple variables in one line

In [ ]:
var1, var2, var3 = "School", "College", "Company"
print(var1,var2,var3)

In [ ]:
var1, var2 ,var3 = "abhi", "shek", "tarn"
print(var1+var2,var3)

- We can also assign multiple variables

In [ ]:
x = y = z = "Mango"
print(x,y,z)

In [ ]:
x = y = z = "Abhishek"
a = "Tarn"
print(x+" "+ a)
print(x,y,z)

In [ ]:
# can we diff fruit ---task----

- We can change the output of a variable just by combining some text in the output statement

In [ ]:
x = "Awesome"
print("The day was "+x) # we just added some text before our variable so that it can make scence

In [ ]:
a,b = "great","rajpura" 
print("my last day was "+a+ ".i visited nalas shiv madir,"+b)

In [ ]:
"""We can't add a two variables contaning string and intiger in them"""

# <span style='color:blue'> Data Types in Python </span>
 ---

## Build-in Data Types

Python has the folloeing data types build-in by default
- Text Type:	str
- Numeric Types:	int, float, complex
- Sequence Types:	list, tuple, range
- Mapping Type:	dict
- Set Types:	set, frozenset
- Boolean Type:	bool
- Binary Types:	bytes, bytearray, memoryview

## Python Numbers and their Casting



```
# This is formatted as code
```

There are 3 typr of numbers in python:
- Int
- Float
- Complex

In [ ]:
# Here we are assigning numbers to some variables of different numbers
x = 2     # int
y = 2.0   # float
z = 1j    # complex ( it is in the form of "ij" where "i" is an int and j is an imaginary number)
# now if we print the type of variables they are.
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>

In [ ]:
a = 2 
b = 2.0
c = 2j
print(type(a)) 
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'complex'>

- Type Casting of numbers

In [ ]:
# We can change the type of numbers just by putting its new type followed by the number
num = 10
num1 = float(num)
num2 = complex(num)  # it will changr the int and add "ij" to it to make it complex type
print(num1)
print(num2)

10.0
(10+0j)

In [ ]:
num = 100
num1 = float(num)
num2 = complex(num)
print(num1)
print(num2)

100.0
(100+0j)

In [ ]:
# We can also create a number instantly and give it a type
number = int(5)
number1 = float(5.0)
number2 = complex(5j)

## <span style='color:blue'> Python Strings </span>

A string is traditionally a sequence of characters, either as a literal constant or as some kind of variable. Strings in python are surrounded by either single quotation marks, or double quotation marks.

In [ ]:
# assigning 
string = "My name is James"
string1 = 'My name is James'
# here the variable string and string1 is same
print(string)
print(string1)

My name is James
My name is James

In [ ]:
# we can also have multiple line string by just putting triple quotes
string2 = """Hello everyone,
My name is James,
I love python"""
print(string2)

Hello everyone,
My name is James,
I love python

- Taking input form user

In [ ]:
string_usr = input("Enter a string: ")
print(string_usr)

- Checking the length of a string

In [ ]:
# len() function is used to find the length of a string by passing the name of that string through it 
# e.g.
st = "Hello everyone"
len(st)

- Accessing elements of a string

In [ ]:
""" We can access elements of string just by putting the name of that variable followed by the square brackets
  and then its index number"""
# e.g.
string = "I love python"
print(string[5])

### Slicing Strings

In [ ]:
# we can also thake the part of a string and print it just by giving the range of index
string[3:9] # it will start from 3 and will print the value until the index value 8

In [ ]:
# if we want to print a string from start to some point or or from some point to end
print(string[:5])
print(string[5:])

In [ ]:
# we can also print the whole string by not giving any parameters
string[:]

In [ ]:
# we can also print the value of a strign i.e. in reverse form
print(string[::-1])    # printing whole string reverse
print(string[6:2:-1])  # printing some part of string reverse

### Modifying String

In [ ]:
# We can take a lower case string and convert it to upper case string and vice versa

String_1 = "Hello World"
print(String_1.upper())  # converting to upper case
print(String_1.lower())  # converting to lower case

In [ ]:
str1 = "hiii there my name is abhi"
print(str1.upper())
print(str1.lower())

In [ ]:
# We can also replace white space at beginning or end of any string
String_2 = "       My name is James     "
print(String_2.strip())

In [ ]:
str1 = "     hiiiiiiiii      "
print(str1.strip())

In [ ]:
# Replacing a charactor from a string just by using the replace function and giving old character that we want to change 
# and giving new character that we have to change to
String_3 = "Hello World!"
print(String_3.replace("H", "J"))

In [ ]:
str1 = "hiiii my name is abhi"
print(str1.replace("a","e"))

In [ ]:
# Now comes the spliting of a string
# The split() method splits the string into substrings if it finds instances of the separator
String_4 = "Hello, everyone here"
print(String_4.split(",")) # it seperated the string from "," as we passed the ',' value in parameteres

### String Concatenation

In [ ]:
Str1 = "Hello "
Str2 = "World"
print(Str1 + Str2) # here we added (concatenated) two strings

In [ ]:
\# we can also take space manually in the print statement
print(Str1 + " " + Str2) # here you can see that space between both strings became more as we added another spacebar

### String Format

As we all know that we can't add a number or intiger to a string as it gives error to us. But we can do it using the format() function in python. It is a form of concatination in which we can concatenate numbers with strings.

In [ ]:
age = 21
txt = "My name is Kyrie and i am {} years old." # here we take '{}' in a string where we have to add number
print(txt.format(age)) # passing variable contaning the number through function format()

In [ ]:
# Here's a real life representation of how this string format is used
quantity = 3
item_no = 567
price = 49.95
my_order = "I want {} pieces of item number {} for {} dollars."
print(my_order.format(quantity, item_no, price))   
#   we have to put the parameteres in the sequence
#   in which we have to print them in that string

In [ ]:
quantity = 5
item_no = 600
price = 50.50

In [ ]:
# we can also put the number between curlu braces to specify the possition of each variable when implimented
quantity = 3
item_no = 567
price = 49.95
my_order = "I want to pay {2} dollars for {0} pieces of item {1}."
print(my_order.format(quantity, item_no, price))

- Python has a set of built-in methods that you can use on strings.

![1_m2e4Z2uV06JIrGVEpLLb7w.png](attachment:1_m2e4Z2uV06JIrGVEpLLb7w.png)

***
And there are many more functions
***

## Python Booleans

Booleans represent one of two values: True or False.

In [ ]:
# we can check if our statement is correct or not
print(10 > 5)

In [ ]:
print(9 < 2)

## <span style='color:red'> Exercise </span>

<b>Q1. If str = "This world is very beautiful", write the output of the following:</b>
- str[5:12]
- str[9:2]
- str[::-1]
- str[15:3:-1]

<b>Q2. Write a program wo reverce a string using string slicing.</b>

---

<b>Q3. Take input form user and print first 5 charactor of that string.</b>

# <span style='color:blue'> Python Operators </span>

Operators are used to perform operations on variables and values.

Python divides the operators in the following groups:

- Arithmetic operators
- Assignment operators
- Comparison operators
- Logical operators
- Identity operators
- Membership operators
- Bitwise operators

## Arithmetic Operators
***
Arithmetic operators are used with numeric values to perform common mathematical operations:

![python%20operators%20table%201.png](attachment:python%20operators%20table%201.png)

## Assignment Operators
***
Assignment operators are used to assign values to variables:

![Screenshot%20%2817%29.png](attachment:Screenshot%20%2817%29.png)

## Comparison Operators
***
Comparison operators are used to compare two values:

![Screenshot%20%2818%29.png](attachment:Screenshot%20%2818%29.png)

## Logical Operators
***
Logical operators are used to combine conditional statements:

![Screenshot%20%2819%29.png](attachment:Screenshot%20%2819%29.png)

## Identity Operators
***
Identity operators are used to compare the objects, not if they are equal, but if they are actually the same object, with the same memory location:



```
# This is formatted as code
```

![Image%201.png](attachment:Image%201.png)

## Membership Operators
***
Membership operators are used to test if a sequence is presented in an object:

![Image%202.png](attachment:Image%202.png)

## Bitwise Operators
***
Bitwise operators are used to compare (binary) numbers:

![Image%203.png](attachment:Image%203.png)

## <span style='color:red'> Exercise </span>

<b>Q1. What is the output of print(10 - 4 * 2)?</b>

In [ ]:
print(10-4*2)

2

<b>Q2. Write the output of print(2 ** 3 ** 2)?</b>

In [ ]:
print(2**3**2)

512

<b>Q.3 Write the output of the following program:</b>

x = 6

y = 2

print(x ** y)

print(x // y)

# <span style='color:blue'> Python Lists </span>

- Lists are used to store multiple items in a single variable.
- Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.
- Lists are created using square brackets

<b>Some Python List characteristics: </b>
- List items are ordered, changeable, and allow duplicate values.
- List items are indexed, the first item has index [0], the second item has index [1] etc.
- Items  in a list have a defined order, and that order will not change. If you add new items to a list, the new items will be placed at the end of the list.
- The list is changeable, meaning that we can change, add, and remove items in a list after it has been created.
- Since lists are indexed and can have items with the same value

In [ ]:
# creating a simple list 
lists = [1,5,"james","564",True]
print(lists)

[1, 5, 'james', '564', True]

## Accessing List Items

Items in a list can be accessed by using their index numbers just as we do in strings.

In [ ]:
list_1 = ["kanishk","namit","charvi","james"] # here's a list named list_1 with 4 items in it 
print(list_1[2])  # accessing the item at index number 2

charvi

In [ ]:
# we can also have the negetive indexing in list just as strings
list_1 = ["kanishk","namit","charvi","james"]
print(list_1[-1])  # here we printed the item at index -1 (this indexing starts from end of the list to start)

james

## Range of Indexes
You can specify a range of indexes by specifying where to start and where to end the range.
When specifying a range, the return value will be a new list with the specified items.

In [ ]:
list_2 = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"] # declaring a list
print(list_2[2:5])

['cherry', 'orange', 'kiwi']

In [ ]:
# Other operations that can be performed in a list
print(list_2[2:]) # printing items from index 2 till the end of list
print(list_2[:5]) # printing items form start of list to index 4

['cherry', 'orange', 'kiwi', 'melon', 'mango']
['apple', 'banana', 'cherry', 'orange', 'kiwi']

## Changing List Items

To change the value of a specific item in a list, just pass the index of that item and assing new value to it.

In [ ]:
list_3 = ["apple", "banana", "cherry"]
list_3[1] = "kanishk"  # replacing the item at index 1
list_3                 # new list

['apple', 'kanishk', 'cherry']

- We can also change a range of values in a list

In [ ]:
list_4 = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
list_4[2:6] = ["kanishk","james","charvi","kyrie"] # taking a range of index and changing its values
list_4

['apple', 'banana', 'kanishk', 'james', 'charvi', 'kyrie', 'mango']

- Inserting new values between the list using insert function

In [ ]:
names = ["james","stephen","jimmy"]
names.insert(2,"thompson") # inserting new value between a list by giving its index value to which we have to insert it
names

['james', 'stephen', 'thompson', 'jimmy']

- If we have to insert new value at the end of list we can use append function

In [ ]:
colors = ["white","blue","black"]
colors.append("red")  # just pass the item in it and it will add that item at the end of the list
colors

['white', 'blue', 'black', 'red']

- Extending a list

In [ ]:
city_1 = ["ambala","delhi","mumbai"]
city_2 = ["lucknow","chandigarh","patna"]
city_1.extend(city_2) # giving the name of list which we have to add to current list
city_1

['ambala', 'delhi', 'mumbai', 'lucknow', 'chandigarh', 'patna']

- We can also remove values from a list using remove() function

In [ ]:
material_1 = ["books","notebooks","tablets","students"]
material_1.remove("students") # passing the value which we have to remove from the list
print(material_1)

['books', 'notebooks', 'tablets']

- We can also use pop functions to remove items from a list

In [ ]:
material_1 = ["books","notebooks","tablets","students"]
material_1.pop(1) # just pass the index of that value which we have to remove from that list
print(material_1)

['books', 'tablets', 'students']

- del() function

In [ ]:
# It is also used to remove a value from list
material_1 = ["books","notebooks","tablets","students"]
del material_1[2] # it also takes index as parameter
print(material_1)

['books', 'notebooks', 'students']

- clear() function

In [ ]:
# It deletes all the values from a list 
material_2 = ["books","notebooks","tablets","students"]
material_2.clear() # in this the list remains but its all values are deleted and now the list is empty
print(material_2)

[]

## Sorting

- We can sort a list using sort() function

In [ ]:
fruit_list = ["orange", "mango", "kiwi", "pineapple", "banana"]
fruit_list.sort() # in this example this list is sorted alphabetically 
print(fruit_list)

['banana', 'kiwi', 'mango', 'orange', 'pineapple']

In [ ]:
# we can also perform this operation in list containg int values

In [ ]:
ints = [100, 50, 65, 82, 23]
ints.sort()
print(ints)

[23, 50, 65, 82, 100]

- Sorting list in reverse order

In [ ]:
ints_1 = [3,4,10,56,2,6]
ints_1.sort( reverse = True ) # reverse is set to a boolean value true which states that it should be sorted in reverse
print(ints_1)

[56, 10, 6, 4, 3, 2]

In [ ]:
thislist = ["banana", "Orange", "Kiwi", "cherry"]#thislist follows..... nomenclature
thislist.reverse()
print(thislist)

['cherry', 'Kiwi', 'Orange', 'banana']

- reversing a list regardless of the alphabet

In [ ]:
fruits = ["banana", "Orange", "Kiwi", "cherry"]
fruits.reverse()
print(fruits)

['cherry', 'Kiwi', 'Orange', 'banana']

## Joining Lists

In [ ]:
list_1 = ["a", "b" , "c"]
list_2 = [1, 2, 3]
print(list_1 + list_2)

['a', 'b', 'c', 1, 2, 3]

In [ ]:
# we can also do it using extend() function 
list_1 = ["a", "b" , "c"]
list_2 = [1, 2, 3]
list_1.extend(list_2) # passing the name of list which we want to add to existing list
print(list_1)

['a', 'b', 'c', 1, 2, 3]

## List Methods

![Image%201.png](attachment:Image%201.png)

# <span style='color:blue'> Python Tuples </span>

- Tuples are used to store multiple items in a single variable.
- Tuple is one of 4 built-in data types in Python used to store collections of data.
- A tuple is a collection which is ordered and unchangeable.
- Tuples are written with round brackets.

In [ ]:
# defining a simple tuple
tuples = ("apple", "banana", "cherry")
print(tuples)

('apple', 'banana', 'cherry')

<b>Some Python Tuples characteristics: </b>

- Tuple items are ordered, unchangeable, and allow duplicate values.
- Tuple items are indexed, the first item has index [0], the second item has index [1] etc.
- When we say that tuples are ordered, it means that the items have a defined order, and that order will not change.
- Tuples are unchangeable, meaning that we cannot change, add or remove items after the tuple has been created.

## Changing Tuples Values

Once a tuple is created, you cannot change its values. Tuples are unchangeable, or immutable as it also is called.
But there is a workaround. You can convert the tuple into a list, change the list, and convert the list back into a tuple.

In [ ]:
tuple_1 = ("apple", "banana", "cherry")  # taking a tuple
var_1 = list(tuple_1)                    # changing a tuple to a list 
var_1[1] = "kiwi"                        # changing a value in that list we created in above step
tuple_1 = tuple(var_1)                   # again changing that tuple to list
print(tuple_1)

('apple', 'kiwi', 'cherry')

In [ ]:
# we can add 2 tuples but not a single value to a tuple 
tuple_2 = ("apple", "banana", "cherry")
tuple_3 = ("Tomato",)
tuple_2 += tuple_3
print(tuple_2)

('apple', 'banana', 'cherry', 'Tomato')

We can only use del() function on tuple. If we want to use any other function we have to change that to a list

## Unpacking Tuples

 When we create a tuple, we normally assign values to it. This is called "packing" a tuple, But, in Python, we are also allowed to extract the values back into variables. This is called "unpacking".

In [ ]:
countries = ("India","America","Russia")
(Safron,Blue,White) = countries # these values becomes a variable for the values of above values
print(Safron)
print(Blue)
print(White)

India
America
Russia

## Joining Tuples

- Joining 2 tuples

In [ ]:
tuple1 = ("james","stephon","thompson")
tuple2 = (1, 2, 3)
tuple3 = tuple1 + tuple2
print(tuple3)

('james', 'stephon', 'thompson', 1, 2, 3)

- Multiplying tuples

In [ ]:
fruits = ("apple", "banana", "cherry")
fruits_1 = fruits * 2
print(fruits_1)

('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')

## Tuples Methods

![Image%202.png](attachment:Image%202.png)

# <span style='color:blue'> Python Dictionaries </span>

Dictionaries are used to store data values in key:value pairs.
A dictionary is a collection which is ordered*, changeable and do not allow duplicates.

In [ ]:
dict_1 = {"notebook":"pen","student":"study","wire":55}
print(dict_1["student"]) # printing value using key

study

<b>Some Python Dictionary characteristics: </b>

- Dictionaries are ordered, it means that the items have a defined order, and that order will not change.
- Dictionaries are changeable, meaning that we can change, add or remove items after the dictionary has been created.
- Dictionaries cannot have two items with the same key.

In [ ]:
dict_2 = {"1":"notebook","2":"book","1":"tablet"}
print(dict_2)              
"""it only showed one value of key "1" which as defined later 
as it cant have same key to different values"""

{'1': 'tablet', '2': 'book'}

'it only showed one value of key "1" which as defined later \nas it cant have same key to different values'

## Accessing Items

- We can access the items of a dictionary by referring to its key name, inside square brackets

In [ ]:
cars = {                        # defining a dictionary having 3 keys and 3 values
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
cars["model"]                  # accessing item using its key

'Mustang'

- get() method is also used to get the same results

In [ ]:
cars = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(cars.get("model"))

Mustang

- we can display all the keys present in a dictionary using keys() function

In [ ]:
cars.keys()

dict_keys(['brand', 'model', 'year'])

## Changing Dictionary Values

- We can change the value of a specific item by referring to its key name

In [ ]:
dictionary_1 = {"redmi":"note10","apple":"iphone","samsung":"m-series"}
dictionary_1["samsung"] = "a-series"   # changing the value using key
print(dictionary_1)

{'redmi': 'note10', 'apple': 'iphone', 'samsung': 'a-series'}

- Update method

The update() method will update the dictionary with the items from the given argument.
The argument must be a dictionary, or an iterable object with key:value pairs.

In [ ]:
dictionary_1 = {"redmi":"note10","apple":"iphone","samsung":"m-series"}
dictionary_1.update({"apple":"ipad"})
dictionary_1

{'redmi': 'note10', 'apple': 'ipad', 'samsung': 'm-series'}

## Adding Items

In [ ]:
dictionary_1 = {"redmi":"note10","apple":"iphone","samsung":"m-series"}
dictionary_1["realme"] = "gt-series"        # adding new key and its value
dictionary_1

{'redmi': 'note10',
 'apple': 'iphone',
 'samsung': 'm-series',
 'realme': 'gt-series'}

In [ ]:
# we can also use update() function to add items
dictionary_1.update({"lenovo":"note-series"})
dictionary_1

{'redmi': 'note10',
 'apple': 'iphone',
 'samsung': 'm-series',
 'realme': 'gt-series',
 'lenovo': 'note-series'}

## Removing Items

- pop() function removes the item with the specified key name.

In [ ]:
dict_2 = {"1":"notebook","2":"book","1":"tablet"}
dict_2.pop("2")
dict_2

{'1': 'tablet'}

- popitem() method removes the last inserted item

In [ ]:
dict_2 = {"1":"notebook","2":"book","1":"tablet"}
dict_2.popitem()
dict_2

{'1': 'tablet'}

In [ ]:
"""
del() function deletes whole dictionary,
clear() function deletes all the values present in that dictionary
"""

'\ndel() function deletes whole dictionary,\nclear() function deletes all the values present in that dictionary\n'

- There are also nested dictionaries present in python

In [ ]:
# e.g.
my_family = {
  "child1" : {
    "name" : "Emil",
    "year" : 2006
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2015
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}
my_family

{'child1': {'name': 'Emil', 'year': 2006},
 'child2': {'name': 'Tobias', 'year': 2015},
 'child3': {'name': 'Linus', 'year': 2011}}

## Dictionary Methods

![Image%203.png](attachment:Image%203.png)

# <span style='color:blue'> Python If...Else </span>

First of all we have some usual logical conditions from mathematics in python:
- Equals: a == b
- Not Equals: a != b
- Less than: a < b
- Less than or equal to: a <= b
- Greater than: a > b
- Greater than or equal to: a >= b

Now we will see some conditional statements in python.

## If Condition

This statement is used to check if some condition is fulfilled then only its code will be executed.

In [ ]:
# syntax
#if ( "some condition" ):
    # contitional code ( body of if statement )

In [ ]:
# lets understand it with the help of an example
var1 = 5
var2 = 10
if var1==var2: # checking if var1 is equal to var2 
    print("its equal") # it true then execute this body else exit the condition

In [ ]:
# another example
num1 = 33
num2 = 33
if num2 == num1:
  print("num2 is greater than num1")

num2 is greater than num1

<b> Short hand if statement <b>

If you have only one statement to execute, you can put it on the same line as the if statement.

In [ ]:
# example 
#    if a > b: print("a is greater than b")

<b> Using logics between if statement<b>

In [ ]:
# using and logic 
"""if a > b and b > c:
    body"""

# using or logic
"""if b == c or a == b:
    body"""

'if b == c or a == b:\n    body'

## Else Statement

The else keyword catches anything which isn't caught by the preceding conditions.

In [ ]:
var3 = 24
var4 = 26
if var3 == var4:
    print("They both are equal.")
else:                                  # its used when we want to execute some code when our condition is not fulfilled
    print("They are not equal.")       # else body

They are not equal.

## Elif Statement

- The elif keyword is pythons way of saying "if the previous conditions were not true, then try this condition".
- It is always placed after if statement and before else statement 
- Its not compulsory to add else statement after it.

In [ ]:
var1 = 5
var2 = 10
if var1 > var2:
    print("var1 is greater than var2")
elif var1 < var2:                            # elif statement
    print("var2 is greater than var1")
else:
    print("they are equal")

var2 is greater than var1

## Nested if Statement

We can have if statements inside if statements, this is called nested if statements.

In [ ]:
# example
var1 = 20
var2 = 50
if var1 < var2: # we have a if statement here 
    print("they are equal")
    if (var2 % var1): # in the body of 1st if statement we have the 2nd if 
        print

they are equal

In [ ]:
var1 = 20
var2 = 50
print(var2 % var1)

10

- If statement can't be empty, but if in some case we have an if statement with no content, put "pass" in the body of if to avoid error

## <span style='color:red'> Exercise </span>

<b>Q1. Write the output for the following program:</b>

a = 9

if (a > 5 and a <=10):    

    print("Hello")    
    
else:    

    print("Bye")

<b>Q2. Write a program to check whether an years is leap year or not.</b>

<b>Q3. Build a basic time table that tells the books you have to carry with you on an perticular day. Make sure that the input for the day should be taken from user.</b>

# <span style='color:blue'> Python Loops </span>

Python has two primitive loop commands:

- While loops

- For loops

## While Loop

With the while loop we can execute a set of statements as long as a condition is true.

In [ ]:
# e.g. we are printing hello_world as long as i is less than 10
i = 1
while i < 10:
    print("hello_world")
    i += 1

hello_world
hello_world
hello_world
hello_world
hello_world
hello_world
hello_world
hello_world
hello_world

- Remember to increment the number, or else the loop will continue forever.

With the break statement we can stop the loop even if the while condition is true:

In [ ]:
# e.g. 
number = 10
while number < 15:
    print(i)
    if i == 12:
        break        # using break statement 
    i += 1

12

With the continue statement we can stop the current iteration, and continue with the next:

In [3]:
num = 0
while num < 5:
    num += 1
    if num == 3:
        continue
    print(num)

1
2
4
5

With the else statement we can run a block of code once when the condition no longer is true:

In [ ]:
num1 = 1
while num1 < 6:
    print(num1)
    num1 += 1
else:
    print("num1 is no longer less than 6")

1
2
3
4
5
num1 is no longer less than 6

## For Loop

A for loop is used for iterating over a sequence. With the for loop we can execute a set of statements, once for each item in a list, tuple, set etc.

In [ ]:
colors = ["black","blue","green","red"]
for i in colors:     # taking i as reference of the values in the list colors
    print(i)

black
blue
green
red

- Even strings are iterable objects, they contain a sequence of characters

In [ ]:
for i in "college":
    print(i)

c
o
l
l
e
g
e

- The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and stops before a specified number.

In [ ]:
# e.g. 
for i in range(0,10): # we can also give 3rd parameter to skip the number of items in the range
    print("world")

world
world
world
world
world
world
world
world
world
world

In [ ]:
for i in range(0,11):
  print("abhi")

abhi
abhi
abhi
abhi
abhi
abhi
abhi
abhi
abhi
abhi
abhi

# <span style='color:red'> Exercise </span>

<b>Q1. Write a program to print first 10 natural numbers.</b>

<b>Q2. Write a program to find the sum of the digits of a number accepted from user.</b>

<b>Q3. Write a program to check whether a number is prime or not.</b>

# <span style='color:blue'> Python Functions </span>

- A function is a block of code which only runs when it is called.
- You can pass data, known as parameters, into a function.
- A function can return data as a result.

In python function is defined using the def keyword:

In [ ]:
def func():      # defining a function 
    print("Hello world!")
# calling that function
func()

Hello world!

## Arguments in a function:

- Information can be passed into functions as arguments.
- Arguments are specified after the function name, inside the parentheses. We can add as many arguments as we want, just separate them with a comma.
- The following example has a function with one argument 'name'. When the function is called, we pass along a first name, which is used inside the function to print the full name

In [ ]:
def function_1(name):
    print(name + " world") 
function_1("Hello")

Hello world

By default, a function must be called with the correct number of arguments. Meaning that if our function expects 2 arguments, we have to call the function with 2 arguments, not more, and not less.

If we do not know how many arguments that will be passed into our function, add a * before the parameter name in the function definition. This way the function will receive a tuple of arguments, and can access the items accordingly

In [ ]:
def function_2(*word):
    print("I love " + word[2])

function_2("c++", "java", "python")

I love python

## Passing a List as an Argument
We can send any data types of argument to a function (string, number, list, dictionary etc.), and it will be treated as the same data type inside the function.

In [ ]:
def function(food):
    for x in food:
        print(x)

fruits = ["apple", "banana", "cherry"]

function(fruits)

apple
banana
cherry

- If we want a function to return a value we can just write return in that function

In [ ]:
# e.g.
def function(x):
     return 10 * x

print(function(2))
print(function(5))
print(function(10))

20
50
100

## The pass Statement
Function definitions cannot be empty, but if we for some reason have a function definition with no content, put in the pass statement to avoid getting an error.

In [2]:
def function():
    pass